code/30-launching-ec2/05-lab08-UserData.yaml
workshop/content/30-workshop-part-01/30-launching-ec2/300-lab-08-user-data.md

N/A
+ update workshop to the latest structure
+ update the code working directory

update(user-data): update lab 08 to latest structure

---

workshop/layouts/partials/menu-footer.html

#22 
+ add feedback issue button

add(feedback): Issue #22

---

code/30-launching-ec2/05-lab08-UserData.yaml
code/30-launching-ec2/06-lab08-UserData-Solution.yaml
code/30-launching-ec2/07-lab09-HelperScripts.yaml
code/30-launching-ec2/08-lab09-HelperScripts-Solution.yaml
code/60-setting-up-nested-stack/01-working directory/main.yaml
code/60-setting-up-nested-stack/02-solution/main.yaml

add(metrics): add metrics to track the template usage

---

code/30-launching-ec2/08-lab09-HelperScripts-Solution.yaml
code/60-setting-up-nested-stack/01-working directory/ec2.yaml
code/60-setting-up-nested-stack/02-solution/ec2.yaml
workshop/content/30-workshop-part-01/30-launching-ec2/400-lab-09-helper-scripts.md

fix(cfn-signal): fix cfn-signal flags as per issue #74

---

workshop/content/30-workshop-part-01/30-launching-ec2/400-lab-09-helper-scripts.md

fix(helper-scripts): fix helper scripts flags as per issue #76

---

workshop/content/30-workshop-part-01/20-cloudformation-features/100-lab-02-resources.md

update(resources): add notification to create Default VPC

---

README.md

Update links to the workshop in preparation for domain deprecation.

Update workshop URL

---

workshop/config.toml
workshop/layouts/partials/menu-footer.html

This PR removes google analytics from the hugo website.

Remove google analytics

---

workshop/content/30-workshop-part-01/10-cloudformation-fundamentals/200-lab-01-stack.md

This wasn't indented correctly to display as a code block.

Fix indentation of code sample in Lab 01

---

workshop/content/30-workshop-part-01/10-cloudformation-fundamentals/200-lab-01-stack.md
workshop/content/40-workshop-part-02/30-package-and-deploy/100-lab-12-package-deploy.md

Fixes some typos in the workshop content

Typo fixes

---

workshop/content/30-workshop-part-01/10-cloudformation-fundamentals/100-template-anatomy.md

Fixes #96
This PR adds a short note about the Rules and Hooks sections
of a CloudFormation template.

This commit adds a short note about the Rules and Hooks sections

---

workshop/content/40-workshop-part-02/10-nested-stacks/100-lab-10-nested-stacks.md

*Issue #, if available:* n/a
Added an indent of the Value property under WebsiteURL

Fix indentation

---

workshop/content/_index.md

#102 
This PR adds info banner to landing page to notify customers about the #102 issue and provides temp workaround.

Add bug banner

---

workshop/content/40-workshop-part-02/_index.md

Remove cutom resource links

---

.gitignore
workshop/content/intermediate/templates/package-and-deploy/_index.md

#122
This PR removes "tabs" for multiple shells as learn theme used at the backend is outdated and doesnt render properly.

Remove tabs

---

workshop/config.toml

N/A
This PR updates the toml config file with correct link to edit page. 

Fix link to edit page

---

.bumpversion.cfg

N/A
The version needs to be bumped on `main` branch, then we merge `main` to `release` branch and release. I will update documentation in next PR.

Bump version: 1.5.2 → 1.6.0

---

.bumpversion.cfg
code/solutions/drift-detection/drift-detection-challenge.yaml
code/solutions/drift-detection/drift-detection-workshop.yaml
code/workspace/drift-detection/drift-detection-challenge.yaml
code/workspace/drift-detection/drift-detection-workshop.yaml
workshop/content/intermediate/operations/drift-detection/_index.md

Add Drift Detection workshop content.

Add Drift Detection workshop

---

contentspec.yaml

Updated workshop configuration.

Updated configuration.

---

content/index.ja.md

To : tkimurz
Please review Japanese translation and approve PR, do not merge.
To : AWS UK Solution Builder
Please wait for review to complete before merging.
No need to update verson until merging to main branch.

Translated workshop top page in Japanese

---

content/index.ja.md

This PR adds Japanese translation for the top page.

Translated workshop top page in Japanese (#172)

---

.bumpversion.cfg
content/basics/operations/helper-scripts/index.md
content/basics/operations/multi-region-latest-ami/index.md
content/basics/operations/troubleshooting-provisioning-errors/index.md
content/basics/templates/intrinsic-functions/index.md
content/basics/templates/mappings/index.md
content/basics/templates/outputs/index.md
content/basics/templates/pseudo-parameters/index.md
content/basics/templates/resource-return-values/index.md
content/basics/templates/resources/index.md
content/basics/templates/template-anatomy/index.md
content/basics/templates/template-and-stack/index.md
content/intermediate/operations/understanding-changesets/index.md
content/intermediate/templates/conditions/index.md
content/intermediate/templates/resource-dependencies/index.md

N/A
This PR adds lab duration.

Add lab duration

---

content/basics/operations/session-manager/index.md
content/basics/operations/user-data/index.md
content/basics/templates/flipping-formats-and-cleanup/index.md
content/basics/templates/linting-and-testing/index.md
content/intermediate/templates/layered-stacks/index.md
content/intermediate/templates/nested-stacks/index.md
content/intermediate/templates/package-and-deploy/index.md

This PR adds lab duration. Minor bug fixes.

Update lab duration

---

content/basics/templates/outputs/index.md
content/basics/templates/resources/index.md
content/intermediate/templates/layered-stacks/index.md
content/intermediate/templates/package-and-deploy/index.md
content/intermediate/templates/policy-as-code-with-guard/index.md

- Fix several spelling and grammar errors
- Highlight an issue users may come across when using pip instead of pip3 command
- Fix an output command bug where I couldn't see the output when running the command
No issue created

Corrected several errors (spelling, grammar and functionality)

---

contentspec.yaml

Fix limitations of WS studio. The maximum amount of regions is 3.

Fix content spec

---

.bumpversion.cfg
content/advanced/resource-types/example-in_Python/index.md

Update cleanup info for resource type lab.
- [Y] Added/Updated documentation if applicable.
- [Y] Pre-commit checks passed.
- [Y] Lint and Nag checks passed.
- [Y] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

Update cleanup info for resource type lab

---

.bumpversion.cfg

Bump version: 2.5.0 → 3.0.0

---

content/intermediate/index.ja.md
content/intermediate/operations/drift-detection/index.ja.md
content/intermediate/operations/resource-importing/index.ja.md
content/intermediate/operations/stack-policy-and-prevention-controls/index.ja.md
content/intermediate/operations/understanding-changesets/index.ja.md
content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
content/intermediate/templates/architecting-templates/index.ja.md
content/intermediate/templates/conditions/index.ja.md
content/intermediate/templates/dynamic-references/index.ja.md
content/intermediate/templates/layered-stacks/index.ja.md
content/intermediate/templates/nested-stacks/index.ja.md
content/intermediate/templates/package-and-deploy/index.ja.md
content/intermediate/templates/policy-as-code-with-guard/index.ja.md
content/intermediate/templates/resource-dependencies/index.ja.md

@cmick-aws 
Please review Japanese translation for the intermediate section.

Translation of 'intermediate' section

---

content/intermediate/operations/stacksets/index.ja.md
content/intermediate/templates/languages-extensions/index.ja.md
content/intermediate/templates/looping-over-collections/index.ja.md

@ttymt , In order not to break repository in main branch, I added the 2 new pages from the intermediate section.
We will use this same branch for catchup later.
Please validate file addition.

Added new labs in Intermediate section, before translation

---

content/advanced/modules/consume-example/index.ja.md
content/advanced/modules/create-example/index.ja.md
content/advanced/resource-types/example-in-python/index.ja.md
content/advanced/resource-types/example-in-python/index.md
content/advanced/resource-types/prerequisites/index.ja.md

@ttymt , please review Japanese translation catch-up for Advanced Lab.

Catch-up for Advanced Lab for Japanese translation

---

content/basics/templates/linting-and-testing/index.md

This fixes some broken links in the Linting and testing page.
#256 

Fix broken links

---

content/basics/templates/linting-and-testing/index.ja.md
content/basics/templates/linting-and-testing/index.md

Fix broken links in English and Japanese versions of Linting and testing lab.
Issue #256
Completes PR #257 

Broken links fix in Linting and testing lab (Issue #256)

---

content/advanced/hooks/lambda-hooks/Cleanup/index.ja.md
content/advanced/hooks/lambda-hooks/Cleanup/index.md
content/advanced/hooks/lambda-hooks/activate-lambda-hook/index.ja.md
content/advanced/hooks/lambda-hooks/activate-lambda-hook/index.md
content/advanced/hooks/lambda-hooks/deploy-lambda-function-for-hook/index.ja.md
content/advanced/hooks/lambda-hooks/deploy-lambda-function-for-hook/index.md
content/advanced/hooks/lambda-hooks/index.ja.md
content/advanced/hooks/lambda-hooks/index.md
content/advanced/hooks/lambda-hooks/prepare-lambda-hook/index.ja.md
content/advanced/hooks/lambda-hooks/prepare-lambda-hook/index.md
content/advanced/hooks/lambda-hooks/test-lambda-hook/index.ja.md
content/advanced/hooks/lambda-hooks/test-lambda-hook/index.md

[Draft] Lambda hooks feedback

---

.bumpversion.cfg
contentspec.yaml

This PR updates the `contentspec` file as well as bumps the version to trigger new build due to an previous internal issue.

Update contenspec file
